/*
Emulator
Name : E V Sai Chathurya
Roll No. : 2401CS84
Declaration of Authorship : This program is my own work and has not been copied from any source
*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <stdint.h>
#include <errno.h>

#define MEM_SIZE 4096          // Total memory size (number of 32-bit words)
#define INSTR_LIMIT 10000000L  // Limit to prevent infinite program execution

// Main memory of the emulator
static int32_t mem[MEM_SIZE];

// CPU registers
static int32_t A  = 0;   // Accumulator register
static int32_t B  = 0;   // Secondary register
static int32_t PC = 0;   // Program Counter
static int32_t SP = 0;   // Stack Pointer

// Extract the opcode (lower 8 bits) from a 32-bit instruction
static inline int get_opcode(int32_t word){
    return (int)((uint32_t)word & 0xFF);
}

// Extract the 24-bit operand and sign extend it to 32 bits
static inline int32_t get_operand(int32_t word){
    uint32_t raw = ((uint32_t)word >> 8) & 0xFFFFFF;

    // Sign extension for negative values
    if(raw & 0x800000)
        raw |= 0xFF000000;

    return (int32_t)raw;
}

// Checks whether a memory address is valid before accessing it
static void mem_check(int32_t addr,const char *op){
    if(addr < 0 || addr >= MEM_SIZE){
        fprintf(stderr,"RUNTIME ERROR: %s address %d out of bounds\n",op,addr);
        exit(EXIT_FAILURE);
    }
}

// Loads the object (.o) file generated by the assembler into memory
static int load_object(const char *filename){

    FILE *fp = fopen(filename,"rb");

    if(!fp){
        fprintf(stderr,"Cannot open '%s'\n",filename);
        return -1;
    }

    int count = 0; // no. of instructions loaded

    // Read instructions one word (4 bytes) at a time
    while(fread(&mem[count],sizeof(int32_t),1,fp)==1){ // fread() = reads binary data from a file into memory

        count++;

        // Ensure program does not exceed available memory
        if(count >= MEM_SIZE){
            fprintf(stderr,"Program too large for memory\n");
            fclose(fp);
            return -1;
        }
    }

    fclose(fp);

    // Return number of instructions loaded
    return count;
}

// Prints all memory locations which contain non-zero values
// Useful for seeing results of programs like sorting algorithms
static void memory_dump(){

    printf("\n--- Memory Dump (non-zero locations) ---\n");

    for(int i=0;i<MEM_SIZE;i++){
        if(mem[i]!=0){
            printf("memory[%d] = %d (0x%08X)\n",i,mem[i],(uint32_t)mem[i]);
        }
    }
}

// Main execution loop of the emulator
static void run(){

    long instr_count = 0;   // Count number of executed instructions

    while(1){ // infinite loop until HALT

        // Check if program counter goes outside memory
        if(PC < 0 || PC >= MEM_SIZE){
            fprintf(stderr,"ERROR: PC out of bounds (%d)\n",PC);
            exit(EXIT_FAILURE);
        }

        // Fetch instruction from memory
        int32_t word = mem[PC];

        // Increment PC (as instruction is being executed)
        PC++;

        // Decode instruction
        int opcode = get_opcode(word);
        int32_t operand = get_operand(word);

        instr_count++;

        // Prevent infinite loops
        if(instr_count > INSTR_LIMIT){
            fprintf(stderr,"ERROR: instruction limit exceeded (infinite loop?)\n");
            exit(EXIT_FAILURE);
        }

        // Execute instruction based on opcode
        switch(opcode){

        case 0: // ldc  : Load constant → B = A , A = operand
            B = A;
            A = operand;
            break;

        case 1: // adc : Add constant → A = A + operand
            A = A + operand;
            break;

        case 2: // ldl : Load local value from stack
            B = A;
            mem_check(SP + operand,"ldl");
            A = mem[SP + operand];
            break;

        case 3: // stl : Store local value to stack
            mem_check(SP + operand,"stl");
            mem[SP + operand] = A;
            A = B;
            break;

        case 4: // ldnl : Load non-local value
            mem_check(A + operand,"ldnl");
            A = mem[A + operand];
            break;

        case 5: // stnl : Store non-local value
            mem_check(A + operand,"stnl");
            mem[A + operand] = B;
            break;

        case 6: // add : A = B + A
            A = B + A;
            break;

        case 7: // sub : A = B - A
            A = B - A;
            break;

        case 8: // shl : Shift left
            A = B << A;
            break;

        case 9: // shr : Shift right
            A = B >> A;
            break;

        case 10: // adj : Adjust stack pointer
            SP = SP + operand;
            break;

        case 11: // a2sp : Move A to SP
            SP = A;
            A = B;
            break;

        case 12: // sp2a : Move SP to A
            B = A;
            A = SP;
            break;

        case 13: // call : Function call
            B = A;
            A = PC;
            PC = PC + operand;
            break;

        case 14: // return : Return from function
            PC = A;
            A = B;
            break;

        case 15: // brz : Branch if A == 0
            if(A == 0)
                PC = PC + operand;
            break;

        case 16: // brlz : Branch if A < 0
            if(A < 0)
                PC = PC + operand;
            break;

        case 17: // br : Unconditional branch
            PC = PC + operand;
            break;

        case 18: // HALT : Stop execution

            printf("\nHALT reached\n");

            printf("Final Registers:\n");
            printf("A = %d\n",A);
            printf("B = %d\n",B);
            printf("PC = %d\n",PC);
            printf("SP = %d\n",SP);

            // Show memory contents after program execution
            memory_dump();

            return;

        default:

            fprintf(stderr,"ERROR: unknown opcode %d\n",opcode);
            exit(EXIT_FAILURE);
        }
    }
}

int main(int argc,char *argv[]){

    // Check if object file is provided
    if(argc < 2){
        printf("Usage: ./emu program.o\n");
        return 1;
    }

    // Initialize memory with zeros
    for(int i=0;i<MEM_SIZE;i++)
        mem[i]=0;

    // Load object file into memory
    int words = load_object(argv[1]); // words = no. of instructions loaded

    if(words < 0)
        return 1;

    printf("Loaded %d instructions\n",words);

    // Start execution
    run();

    printf("\n--- Program Finished ---\n");
    printf("Final Registers:\n");
    printf("A = %d\n",A);
    printf("B = %d\n",B);
    printf("PC = %d\n",PC);
    printf("SP = %d\n",SP);

    memory_dump();  

    return 0;
}